In [7]:
import sys
import numpy as np
import cv2

In [2]:
mat = np.array([
    [0,0,1,1,0,0,0,0],
    [1,1,1,1,0,0,1,0],
    [1,1,1,1,0,0,0,0],
    [0,0,0,0,0,1,1,0],
    [0,0,0,1,1,1,1,0],
    [0,0,1,1,0,0,1,0],
    [0,0,1,1,1,1,1,0],
    [0,0,0,0,0,0,0,0]] , np.uint8)
    

In [3]:
cnt, labels = cv2.connectedComponents(mat)

In [4]:
print('sep', mat, sep='\n')
print('cnt',  cnt)
print('labels' , labels ,sep ='\n')

sep
[[0 0 1 1 0 0 0 0]
 [1 1 1 1 0 0 1 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 1 0]
 [0 0 0 1 1 1 1 0]
 [0 0 1 1 0 0 1 0]
 [0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0]]
cnt 4
labels
[[0 0 1 1 0 0 0 0]
 [1 1 1 1 0 0 2 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 0 3 3 0]
 [0 0 0 3 3 3 3 0]
 [0 0 3 3 0 0 3 0]
 [0 0 3 3 3 3 3 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
src = cv2.imread('../data/keyboard.bmp', cv2.IMREAD_GRAYSCALE)

if src is None:
    print('image load failed')
    sys.exit()
    
_, src_bin = cv2.threshold(src, 0 , 255, cv2.THRESH_OTSU)

cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(src_bin)

dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

for i in range(1, cnt):
    (x,y,w,h,area) = stats[i]

In [11]:
import random

src = cv2.imread('../data/contours.bmp', cv2.IMREAD_GRAYSCALE)

if src is None:
    print('image load failed')
    sys.exit()


contours , hier = cv2.findContours(src, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
## 외곽선 검출 모드, 외곽선 근사화 방법 

dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

idx = 0
while idx >= 0:
    c = (random.randint(0,255), random.randint(0,255), random.randint(0,255))
    cv2.drawContours(dst, contours, idx,  c, 2, cv2.LINE_8, hier)
    idx = hier[0,  idx , 0 ]
 
 
    
cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
src = cv2.imread('../data/milkdrop.bmp', cv2.IMREAD_GRAYSCALE)

if src is None:
    print('image load failed')
    sys.exit()
    
_, src_bin = cv2.threshold(src, 0 , 255, cv2.THRESH_OTSU)


contours , _ = cv2.findContours(src_bin, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
## 외곽선 검출 모드, 외곽선 근사화 방법 

h , w = src.shape[:2]
dst = np.zeros((h,w,3), np.uint8)

## dst 빈 이미지에 외곽선을 그리는 방식 
for i in range(len(contours)):
    c = (random.randint(0,255), random.randint(0,255), random.randint(0,255))
    cv2.drawContours(dst, contours, i,  c, 1, cv2.LINE_AA)
    
 
 
    
cv2.imshow('src', src)
cv2.imshow('src_bin', src_bin)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
import math 

def setLabel(img, pts, label):
    (x,y,w,h) = cv2.boundingRect(pts)
    pt1 = (x,y)
    pt2 = (x+w, y+h)
    cv2.rectangle(img, pt1, pt2, (0,0,255), 1)
    cv2.putText(img, label, pt1, cv2.FONT_HERSHEY_PLAIN, 1, (0,0,255))
    
def main():
    img = cv2.imread('../data/polygon.bmp', cv2.IMREAD_COLOR)

    if src is None:
        print('image load failed')
        sys.exit()
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    _,  img_bin = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
    contours , _, = cv2.findContours(img_bin, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    
    for pts in contours:
        if cv2.contourArea(pts) < 400: ## 외곽선이 너무 길이가 작으면 무시하겠다.
            continue ## 반복문과 continue를 활용한 코드 구성
        
        ## 외곽선 근사화 
        approx = cv2.approxPolyDP(pts, cv2.arcLength(pts, True)*0.02, True)
        
        vtc =  len(approx)
        
        if vtc == 3:
            setLabel(img, pts, 'TRI')
        elif vtc == 4:
            setLabel(img, pts, 'retc')
        else:
            length = cv2.arcLength(pts, True)
            area = cv2.contourArea(pts)
            ratio = 4. * math.pi * area / (length* length)
            
            if ratio > 0.85:
                setLabel(img, pts, 'Circle')

    cv2.imshow('img' , img)
    cv2.waitKey()
    cv2.destroyAllWindows()
         
        
if __name__ == '__main__':
    main()
